# Generated by Django 4.1.6 on 2023-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptId', models.CharField(max_length=10)),
                ('deptName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=10)),
                ('empName', models.CharField(max_length=100)),
                ('empDept', models.CharField(max_length=10)),
                ('empJoinDate', models.DateField()),
                ('empPhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
